export const defaultSchema = [
  {
    attr: 672,
    canTrigger: false,
    code: 'switch_go',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-power',
    id: 1,
    mode: 'rw',
    name: '清扫开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 672,
    canTrigger: false,
    code: 'pause',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_pause',
    id: 2,
    mode: 'rw',
    name: '暂停/继续',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 160,
    canTrigger: false,
    code: 'switch_charge',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-a_power',
    id: 3,
    mode: 'rw',
    name: '回充开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 704,
    canTrigger: true,
    code: 'mode',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 4,
    mode: 'rw',
    name: '工作模式',
    property: {
      range: ['smart', 'goto_charge', 'zone', 'pose', 'part', 'select_room'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 706,
    canTrigger: true,
    code: 'status',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 5,
    mode: 'ro',
    name: '机器状态:',
    property: {
      range: [
        'standby',
        'smart',
        'zone_clean',
        'part_clean',
        'cleaning',
        'paused',
        'goto_pos',
        'pos_arrived',
        'pos_unarrive',
        'goto_charge',
        'charging',
        'charge_done',
        'sleep',
        'select_room',
        'seek_dust_bucket',
        'collecting_dust',
        'mapping',
        'mapping_done',
        'broken_gocharge',
        'broken_charing',
        'low_battery_gocharge',
        'goto_washmop',
        'mop_cleaning',
        'mop_drying',
        'cut_hair',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'clean_time',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 6,
    mode: 'ro',
    name: '清扫时间',
    property: {
      unit: 'min',
      min: 0,
      max: 9999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'clean_area',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-icon-test10',
    id: 7,
    mode: 'ro',
    name: '清扫面积',
    property: {
      unit: '㎡',
      min: 0,
      max: 9999,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 194,
    canTrigger: true,
    code: 'battery_percentage',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_battery',
    id: 8,
    mode: 'ro',
    name: '剩余电量',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'suction',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-Strong',
    id: 9,
    mode: 'rw',
    name: '吸力选择',
    property: {
      range: ['closed', 'gentle', 'normal', 'strong', 'max'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'cistern',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_water',
    id: 10,
    mode: 'rw',
    name: '水量选择',
    property: {
      range: ['closed', 'low', 'middle', 'high'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'seek',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_magnifier',
    id: 11,
    mode: 'rw',
    name: '寻找机器',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1248,
    canTrigger: false,
    code: 'direction_control',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_compass',
    id: 12,
    mode: 'rw',
    name: '方向',
    property: {
      range: ['forward', 'backward', 'turn_left', 'turn_right', 'stop', 'exit'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'map_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_loop',
    id: 13,
    mode: 'rw',
    name: '重置地图',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'path_data',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_fly',
    id: 14,
    mode: 'rw',
    name: '路径传输',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'command_trans',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_fly',
    id: 15,
    mode: 'rw',
    name: '指令传输',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'request',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 16,
    mode: 'rw',
    name: '请求数据',
    property: {
      range: ['get_map', 'get_path', 'get_both'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'edge_brush_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-icon-percent',
    id: 17,
    mode: 'rw',
    name: '边刷剩余寿命',
    property: {
      unit: 'min',
      min: 0,
      max: 10800,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 160,
    canTrigger: false,
    code: 'edge_brush_life_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_loop',
    id: 18,
    mode: 'rw',
    name: '边刷重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'roll_brush_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-icon-percent',
    id: 19,
    mode: 'rw',
    name: '滚刷剩余寿命',
    property: {
      unit: 'min',
      min: 0,
      max: 21600,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 160,
    canTrigger: false,
    code: 'roll_brush_life_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_loop',
    id: 20,
    mode: 'rw',
    name: '滚刷重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'filter_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time2',
    id: 21,
    mode: 'ro',
    name: '滤芯剩余寿命',
    property: {
      unit: 'min',
      min: 0,
      max: 10800,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 160,
    canTrigger: false,
    code: 'filter_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_loop',
    id: 22,
    mode: 'rw',
    name: '滤网重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'rag_life',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-icon-percent',
    id: 23,
    mode: 'ro',
    name: '拖布剩余寿命',
    property: {
      unit: 'min',
      min: 0,
      max: 10800,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 160,
    canTrigger: false,
    code: 'rag_life_reset',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_loop',
    id: 24,
    mode: 'rw',
    name: '拖布重置',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'do_not_disturb',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 25,
    mode: 'rw',
    name: '勿扰开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'volume_set',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_voice',
    id: 26,
    mode: 'rw',
    name: '音量设置',
    property: {
      unit: '%',
      min: 0,
      max: 100,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'break_clean',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_wash',
    id: 27,
    mode: 'rw',
    name: '断点续扫',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1728,
    canTrigger: true,
    code: 'fault',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-baojing',
    id: 28,
    mode: 'rw',
    name: '故障告警',
    property: {
      label: [
        'low_power',
        'low_power_off',
        'long_idle_power_off',
        'escape_failed',
        'wheel_up',
        'path_plan_failed',
        'part_area_navi_fail',
        'forbit_zone_start',
        'go_dock_failed',
        'fail_to_locate',
        'mopping_lost',
        'water_box_fault',
        'clean_bracket_lost',
        'dirt_water_box_fault',
        'dust_bag_lost',
        'roll_brush',
        'side_brush',
        'motor_current_over',
        'cliff_ir',
        'lidar_shelter',
        'sewage_tank_full',
        'cut_hair_failed',
        'dust_box_lost',
        'slope_start',
        'dust_frequence',
        'co_sensor',
        'mop_block',
      ],
      type: 'bitmap',
      maxlen: 27,
    },
    scope: 'fault',
    type: 'obj',
  },
  {
    attr: 224,
    canTrigger: false,
    code: 'device_timer',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time2',
    id: 32,
    mode: 'rw',
    name: '定时',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 224,
    canTrigger: false,
    code: 'disturb_time_set',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 33,
    mode: 'rw',
    name: '勿扰时间设置',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 224,
    canTrigger: false,
    code: 'device_info',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 34,
    mode: 'ro',
    name: '设备信息',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 224,
    canTrigger: false,
    code: 'voice_data',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 35,
    mode: 'rw',
    name: '语音包数据下发',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 1248,
    canTrigger: false,
    code: 'language',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 36,
    mode: 'rw',
    name: '语音选择',
    property: {
      range: [
        'chinese_simplified',
        'chinese_traditional',
        'english',
        'german',
        'french',
        'russian',
        'spanish',
        'korean',
        'latin',
        'portuguese',
        'japanese',
        'italian',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1216,
    canTrigger: true,
    code: 'dust_collection_num',
    defaultRecommend: false,
    editPermission: true,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_wash',
    id: 37,
    mode: 'rw',
    name: '集尘频率设置',
    property: {
      unit: '',
      min: 0,
      max: 3,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 160,
    canTrigger: false,
    code: 'dust_collection_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 38,
    mode: 'rw',
    name: '集尘宝',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'customize_mode_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 39,
    mode: 'rw',
    name: '自定义模式',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'mop_state',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 40,
    mode: 'ro',
    name: '拖布状态',
    property: {
      range: ['none', 'installed'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'work_mode',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 41,
    mode: 'rw',
    name: '工作模式',
    property: {
      range: ['both_work', 'only_sweep', 'only_mop', 'sweep_after_mop'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'carpet_clean_prefer',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 44,
    mode: 'rw',
    name: '地毯清洁偏好',
    property: {
      range: ['adaptive', 'evade'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'auto_boost',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_up',
    id: 45,
    mode: 'rw',
    name: '地毯增压',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'child_lock',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 47,
    mode: 'rw',
    name: '按键童锁',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'y_mop',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-a_mode_dry',
    id: 48,
    mode: 'rw',
    name: 'Y字型拖地',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'self_clean',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_wash',
    id: 49,
    mode: 'rw',
    name: '拖布自清洁',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'drying',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-jiare',
    id: 50,
    mode: 'rw',
    name: '烘干开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'self_clean_frequency',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_smile',
    id: 51,
    mode: 'rw',
    name: '拖布自清洁频率',
    property: {
      unit: 'min',
      min: 10,
      max: 30,
      scale: 0,
      step: 5,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'back_wash_by_room',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 101,
    mode: 'rw',
    name: '拖布房间回洗模式',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'auto_motor_stretch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 102,
    mode: 'rw',
    name: '拖布外摆',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'auto_cut_hair',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 103,
    mode: 'rw',
    name: '自动割毛发',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'auto_wash_mop',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 104,
    mode: 'rw',
    name: '自动洗拖布',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'hot_water_mop',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 105,
    mode: 'rw',
    name: '热水洗拖布',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'auto_add_cleansingfluid',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 106,
    mode: 'rw',
    name: '自动添加清洗液',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'ai_detection',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 107,
    mode: 'rw',
    name: 'AI识别总开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'ai_obstacle_avoidance',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 111,
    mode: 'rw',
    name: 'Ai避障',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'ai_agent_clean',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 112,
    mode: 'rw',
    name: 'AI托管清洁',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'dry_duration',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 113,
    mode: 'rw',
    name: '烘干时长',
    property: {
      unit: 'H',
      min: 2,
      max: 4,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'cut_hair_frequence',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 114,
    mode: 'rw',
    name: '割毛发频次',
    property: {
      unit: '次',
      min: 1,
      max: 5,
      scale: 0,
      step: 2,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'cut_hair',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 115,
    mode: 'rw',
    name: '一键割毛发',
    property: {
      range: ['off', 'on'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'dry',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 116,
    mode: 'rw',
    name: '一键烘干',
    property: {
      range: ['off', 'on'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'mop_stretch_freq',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 117,
    mode: 'rw',
    name: '拖布外摆频次',
    property: {
      unit: '次',
      min: 1,
      max: 5,
      scale: 0,
      step: 2,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'repeat_clean',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 118,
    mode: 'rw',
    name: '二次清扫',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
] as const;
